[variables]
NODE_ENV = 'production'

[phases.setup]
nixPkgs = ['nodejs-20_x']

[phases.install]
cmds = ['npm install --production']

[phases.build]
cmds = ['echo "No build step required for Node.js backend"']

[start]
cmd = 'npm start'