[variables]
NODE_ENV = 'production'

[phases.setup]
nixPkgs = ['nodejs-20_x']

[phases.install]
cmds = ['cd backend && npm ci --only=production']

[phases.build]
cmds = ['echo "No build step required for Node.js backend"']

[start]
cmd = 'cd backend && npm start'