[variables]
NODE_ENV = 'production'

[phases.setup]
nixPkgs = ['nodejs-20_x']

[phases.install]
cmds = [
  'pwd',
  'ls -la',
  'cd backend',
  'pwd',
  'ls -la',
  'cat package.json',
  'npm install --production --no-optional',
  'ls -la node_modules',
  'echo "Dependencies installed successfully"'
]

[phases.build]
cmds = ['echo "No build step required for Node.js backend"']

[start]
cmd = 'cd backend && npm start'