[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
