[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[environments.production.build]
buildCommand = "npm install"
